### ISSUE TITLE
CoL of June 2021: plans & tests

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#121]
- [x] **At! Re-do all syncs for GSDs previously completed between 2021-05-11 - 21**

**New datasets:**
- [x] WoRMS Crinoidea - synced 2021-05-13, 2021-05-26, re-synced **2021-06-16**
- [x] WoRMS Nematoda, Nemys - synced 2021-05-13, 2021-05-26, re-synced **2021-06-16**
- [x] WoRMS Brachiopoda (replacement for Brachiopoda by Emig & al.) - synced 2021-05-13, 2021-05-26, re-synced **2021-06-16**
- [x] WoRMS Euphausiacea (replacement for ETI Euphausiacea) - synced 2021-05-13, 2021-05-26, re-synced **2021-06-16**

**?? Datasets have been updated:**
- [x] all WoRMS checklists (60+4, 2nd update of 2021-06-01) - synced 2021-06-07); Nemys, Crinoidea, Euphausiacea, Brachiopoda, Turbellarians (logo corrected) re-synced **2021-06-16**
- [x] ITIS (9th update of 2021-05-26; new sectors: family Smarididae, superfamily Calyptostomatoidea, infraorder Stenopodidea) - synced 2021-06-07
- [x] Alucitoidea (5th update), 2021-05-26 
- [x] Pterophoroidea (4th update), 2021-05-26 
- [x] Eumycetozoa of 2021-04-15 (imported on prod). Experimental sync with unresolved "splits" 2021-05-13. Resolved. - Final sync 2021-05-19, 2021-05-26
- [x] Systema Dipterorum (ready on dev; ~~latest ver awaiting~~ ver 3.1 received; CIPA go for retirement)
**imported on prod** https://data.catalogueoflife.org/dataset/1101/about - synced 2021-05-17, 2021-05-26, re-synced **2021-06-18**
- [x] CCW of 2021-05-07 (**imported on prod** https://data.catalogueoflife.org/dataset/1005/about) - synced 2021-05-14. Missing synonyms reported by Pjotr - FIXED - synced 2021-05-25, 2021-05-26
- [x] WPlants (5th update) of 2021-05-10 (**imported on prod**) - ~~synced 2021-05-19. Updated with 375a 2021-05-24.~~ Synced 2021-05-26
- [x] WFerns (6th update) of 2021-05-10 (**imported on prod**) - synced 2021-05-19, 2021-05-26
- [x] Brassicaceae ("Update on the Brassicaceae Species Checklist" id 2305) on prod - synced with reported problems (https://github.com/CatalogueOfLife/testing/issues/130) 2021-05-19; re-synced with blocked accepted trinomials 2021-05-25
- [x] ReptileDB imported on prod 2021-05-24 - synced 2021-05-24, 2021-05-26; ver of  2021-05-23 synced **2021-06-24**
- [x] Scarabs of 2021-06-01, 10th update - synced 2021-06-07

**For next releases:**
- [ ] WTaxa (ready on dev; should go alongside with 3i Curculio)
- [ ] 3i Curculio new ver. available at SFG 2021-05-24; postponed as all TW updates
- [ ] 3i Auchenorrhyncha postponed as all TW updates
- [ ] SFs postponed as all TW updates
- [ ] CarabCat. Data for test received on 2021-05-20 
- [ ] FishBase (not received)
- [ ] IRMNG of 2021-05-11 (imported on dev & prod) - Cannot be included in ac21 right now. Requires review by Taxonomy Group and additional work. 

**FIX UPDATE-BLOCK PROBLEM**
- [x] see https://github.com/CatalogueOfLife/testing/issues/133 - fix decisions made between May 11-21. DECISIONS FIXED 2021-05-25 by @mdoering

**Comment by yroskov** [comment]
Mn, 2021-05-24:
- ReptileDB to prod
- SFs to prod
- 3i Curculio to dev
- WPlants update 375a

**Comment by yroskov** [comment]
**CCW:**

Pjotr has checked PREVIEW of 2021-05-19 and reported (eml to @yroskov of 2021-05-22):

    A search for the synomym “jaroslavi” give the proper result
    But a search for the synonym Tipula solstitialis gives no result.

Indeed, the system marked Tipula (Yamatotipula) solstitialis Westhoff, 1879 as bare name: https://data.catalogueoflife.org/dataset/1005/name/17778

https://github.com/CatalogueOfLife/testing/issues/120#issuecomment-847291440

**Comment by yroskov** [comment]
**World Plants:**

Dear Yury, in Caryophyllaceae there is an **embarrassing error in genus Sabulina**. Could you please exchange family data against attached file?

YR: file received, data will be updated.

**Comment by yroskov** [comment]
From: Roskov, Yury 
Sent: Wednesday, May 26, 2021 16:53
To: Olaf Bánki Ower, Geoffrey Donald Markus Döring Thomas Stjernegaard Jeppesen Chantal Huijbers 
Cc: Dewalt, R Edward 
Subject: RE: COL Checklist 2021 planning

Dear Olaf and Ed,

I am happy to report that assembly of manually managed checklists has been completed by Geoff and me today (May 26th). Ed has agreed that Species Files updates will not appear in the 2021 Annual Checklist, but come in one of next monthly editions. I have kicked off re-syncs for all updated checklists. I hope, sync will be completed tonight. I am expecting, that the CoL will be released to the preview website tomorrow.

This version includes (https://github.com/CatalogueOfLife/testing/issues/121):
4 new checklists:
•	WoRMS Crinoidea
•	WoRMS Nematoda, Nemys
•	WoRMS Brachiopoda (it’s a replacement for Brachiopoda by Emig & al.)
•	WoRMS Euphausiacea (it’s a replacement for ETI Euphausiacea) 
9 checklists have been updated:
•	Alucitoidea (5th update)
•	Brassicaceae
•	CCW
•	Eumycetozoa
•	Pterophoroidea (4th update)
•	ReptileDB
•	Systema Dipterorum
•	World Ferns (6th update)
•	World Plants (5th update)
As you can see, it does not include ITIS of May (the export is not available yet) and new versions of WoRMS (their export is expected on 2021-06-01). It’s up to Olaf to decide, whether June’s CoL/AC will go ahead without these updates or will wait for them. I am expecting that ITIS & WoRMS updates might be completed by Geoff during the next week. My checks and final syncs of ITIS & WoRMS might be completed for June 15th.   

Metadata for all manually assembled and updated checklists have been updated, checked and corrected in the checklistbank between January 2020 and May 2021. Metadata for all checklists imported from AC19 have been checked and corrected in the checklistbank for the release of 2020-01-10 Beta.

Yours, Yuri

**Comment by yroskov** [comment]
SYNCED, as reported above.

**Preview release of 2021-05-27** is available at https://preview.catalogueoflife.org/

**Comment by yroskov** [comment]
ITIS of 2021-05-26, and 64 WoRMS with new JAML metadata imported & synced. WoRMS re-use previously set up decisions.

Preview release of 2021-06-09 is available at https://preview.catalogueoflife.org/

**Comment by yroskov** [comment]
- [ ] ITIS: fix placement (in suborder Pleocyemata instead of NotAssigned) :

Dear Yuri,
Things for the new sectors look good, but I did notice the placement of the following should be under Suborder Pleocyemata rather than under Suborder Not Assigned:
infraorder: Astacidea Latreille, 1802
infraorder: Glypheidea Winkler, 1883

Thanks! Dave

**Comment by yroskov** [comment]
- [ ] WoRMS: kill patches for all WoRMS, except 2302 Nematoda/Nemys

Hi Yuri,

Two remarks: 

1. it looks like you ignore the “organisations” we provide in the metadata YML
i.e. https://preview.catalogueoflife.org/data/dataset/1044
lists only UvA, while we provide 19 institutes (from all editors)

2. license says other, while we provide “CC-BY”

Regards, Bart

**Comment by mdoering** [comment]
Did someone tell Bart yet about the changed metadata.yaml?
`organisations` especially is deprecated and he can place affiliations to institutions directly with the people (creator, editor, contributor)

**Comment by bart-v** [comment]
I don' think many people will be happy to change the metadata format each week...
https://github.com/CatalogueOfLife/coldp/commit/6642c6ab32d6c46a609719d1cfc27ade65e9620e

Is there any attempt to make these things in some way stable?

**Comment by mdoering** [comment]
Yes. This change is actually the attempt to make it stable and release it as a fixed, first version.
We have planned to do this final change for months, see our version 1 milestone here: https://github.com/CatalogueOfLife/coldp/issues?q=is%3Aissue+milestone%3A%22Public+release%22+

And consolidated the metadata model in a longer process with the ISG. See also https://github.com/CatalogueOfLife/backend/issues/989 and related issues.

@bart-v sorry to hear you are surprised by this change. I had expected that you were informed about our ColDP release plans when you first worked on the ColDP export.

Said that, we do silently still support the deprecated format. If you could migrate WoRMS to this v1 metadata format that's appreciated, but things should still be working otherwise.

**Comment by bart-v** [comment]
I was not aware about release plans/timings.
I do get your COL-Users mailing list emails, but yeah...

Anyway, we should be able to deal with it, eventually.

**Comment by mdoering** [comment]
Thanks @bart-v, I thought @gdower or @yroskov had told you when working with you.

**Comment by yroskov** [comment]
I would expect that @bart-v, as a developer of most successful software for biodiversity data and a major data provider in CoL (64 checklists!), should be a member of IT consultation group(s) in CoL/GBIF. His opinion should be taken on board BEFORE any kind of changes in data model. I am surprised, that it was not happened in the case of metadata again.

**Comment by yroskov** [comment]
Preview release with two above fixes has started 2021-06-10.

**Comment by yroskov** [comment]
**CoL of 2021-06-10 deployed to the public portal** on 2021-06-14

2,026,387 acc & prov acc spp

**Comment by yroskov** [comment]
- [ ] 3 GSDs have underscores in their short names:
![image](https://user-images.githubusercontent.com/28574252/122278274-59ba2400-ceac-11eb-9ecd-7bc30470ad78.png)
(4 GSDs with release date 2021-05-01: 3 above + WoRMS Nematoda/Nemys)
re-imported, re-synced 

- [ ] Missing distribution data in WoRMS imports

**Comment by bart-v** [comment]
1.  Underscores are within the CoL system, not in the WoRMS exports.
i.e.
```
--
title: 'World List of Crinoidea'
alias: 'WoRMS Crinoidea'
```
2. Same for distributions: these are being provided, but are not shown within the CoL system
See https://github.com/CatalogueOfLife/testing/issues/119#issuecomment-859027140

**Comment by mdoering** [comment]
The WoRMS short names do not have underscores in CLB, it's just as WoRMS provided them:
https://data.catalogueoflife.org/dataset/2300/about

Maybe there was a patch before or an older version got used?

**Comment by yroskov** [comment]
New preview release with few fixes in Systema Dipterorum kicked off 2021-06-18 at 16.30

**Comment by mdoering** [comment]
Good! Can we please regularly delete the private releases from last month? We had 7 releases in May & June alone. I understand you might want to compare with the previous release, but that would be June. What good are the 3 private May releases now?

**Comment by yroskov** [comment]
Preview **2021-06-18** https://preview.catalogueoflife.org/ looks good.

- [x] Underscores in 4 WoRMS GSDs - FIXED (re-imported & re-synced).
- [x] Missing "extinct" flag in Systema Dipterorum. New spp stats: 145933 extant & 3759 extinct spp.
- [ ] Parent taxa with all extinct children species are not marked as extinct (i.e. no dagger with genus, family, etc.)

**Comment by yroskov** [comment]
**2021-06-24: preview release** started
after resyncs 5 WoRMS Nemys, Crinoidea, Euphausiacea, Brachiopoda, Turbellarians (logo corrected), Systema Dipterorum (with extinct spp), ReptileDB (with acc subspp).
