### ISSUE TITLE
Systema Dipterorum

### ISSUE THREAD

**Issue by fleshflyguy** [CatalogueOfLife/testing#132]
In the metadata, you forgot to change the data for “Organisation”. This should be:

Organisation
Bishop Museum Honolulu, Hawaii, USA
Natural History Museum of Denmark, University of Copenhagen, Denmark

Two questionmarks are given directly on the attached screendumps.
![Screen2](https://user-images.githubusercontent.com/84519886/119002255-01673380-b98d-11eb-9f37-173944e9ff3d.png)
![Screen1](https://user-images.githubusercontent.com/84519886/119002265-0330f700-b98d-11eb-8fc4-9f2e1d737976.png)

**Comment by yroskov** [comment]
- [x] Orgaisation fixed:
