### ISSUE TITLE
WoRMS metadata: field taxonomicScope

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#137]
@bart-v, would it be possible to fill "English name of the group" in the **taxonomicScope** field of metadata?  i.e. instead of scientific name "Ctenophora" for WoRMS Ctenophora put "Comb jellies, sea walnuts" in the field.

I put here screenshots from the past and from now, as an example:
ac19:
![image](https://user-images.githubusercontent.com/28574252/123296529-56dab700-d4dc-11eb-811f-eccd6c3a969d.png)

now:
![image](https://user-images.githubusercontent.com/28574252/123296656-72de5880-d4dc-11eb-953c-08ed7a628cb3.png)

**Comment by bart-v** [comment]
We'll pick the preferred or first English name for that group in WoRMS.
Would that be OK?

**Comment by yroskov** [comment]
Yes, it will be OK. Thanks!

**Comment by bart-v** [comment]
OK, done, available in next export.

**Comment by yroskov** [comment]
Thanks!
