### ISSUE TITLE
CoL of August 2021: tests

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#149]
To do updates:

- [x] Scarabs of 2021-08-04: imported; synced 2021-08-19 
- [x] World Ferns of 2021-08-06: imported; tasks completed; synced 2021-08-19
- [x] CarabCat of ~~2021-08-08~~, 2021-08-20: imported; tasks completed; ~~sector re-establishing is failed; not synced~~; synced 2021-08-20
- [x] Scorpion Files (2021-07-27, a new crawling completed by GO): imported; synced 2021-08-20
- [x] ITIS of 2021-07-26: imported; synced 2021-08-20 (two syncs failed: superfamily Platygastroidea & suborder Oribatida)
- [x] WoRMS of 2021-08-01: imported; synced by GO 2021-08-20
- [x] "Old" ReptileDB re-synced 2021-08-20. Expected 11,570 spp are back (see https://github.com/CatalogueOfLife/testing/issues/129#issuecomment-902804862)
- [x] World Plants of 2021-08-06: imported; tasks completed; synced 2021-08-23

Also available:
- WCVP (Kew)

**Comment by yroskov** [comment]
Priority for September:
- Species Files

**Comment by yroskov** [comment]
Preview release failed 2021-08-20:
![image](https://user-images.githubusercontent.com/28574252/130291980-3521756a-dda9-4b82-9295-da5b63632e1a.png)

**Comment by mdoering** [comment]
just released: https://data.catalogueoflife.org/dataset/2330

**Comment by yroskov** [comment]
**Preview release 2021-08-24** at https://preview.catalogueoflife.org/ 

- [x] All spp 2016692 vs 2008947 of 2021-07-29 = +7,745
- [x] **ReptileDB** fixed: 11570/0 spp as would expected
- [ ] **Strepsiptera** checklist is credited as Strepsiptera Database https://preview.catalogueoflife.org/data/dataset/1103, not as WoRMS Strepsiptera in 2021-07-29. The checklist & metadata are identical to those in ac19.

**Comment by yroskov** [comment]
- [x] Strepsiptera (id1103) re-synced 2021-08-25 (due to incorrect short name/alias. Should be WoRMS Strepsiptera)
- [x] Species Fungorum Plus (id2073) re-synced 2021-08-25 (due to incorrect short name/alias. Should be Species Fungorum Plus)
