### ISSUE TITLE
WSVP: missing parent-child links between species and subspecies/varieties?

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#189]
@mdoering, doing tests of CoL-Preview 2022-04-01 (https://github.com/CatalogueOfLife/testing/issues/177#issuecomment-1086205610), I have spotted a problem in WSVP dataset. It looks like there are no parent-child relationships between species and subspecies/varieties in the imported dataset. Perghaps, CLB establishes these relationships during sync. As a result, there are two entries for parent species in final CoL (one with auithorstring, but without subspecies, second without authorstring, but with children subspecies). Neither of their species pages are accessible (Error code 500). 

Below there are few names as examples of the case.

**Acorus calamus** appears twice in the search. But it's a single entry in CLB. Why? Is it isolated case, or common? = **No, seems, it is common case for all species with subspecies/varieties. Are subspecies/vars properly linked to parent species in the imported dataset?** 

(Choice of first or second item resulted with Error code 500, message "There was an error processing your request. It has been logged (ID 1401e196cbc64eb9).")

![image](https://user-images.githubusercontent.com/28574252/161320501-31ec5fd3-c1bc-40e8-bbfd-7490b1859086.png)

In CLB: https://www.checklistbank.org/dataset/2232/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&q=acorus%20calamus&sortBy=taxonomic&status=accepted
![image](https://user-images.githubusercontent.com/28574252/161320763-7ac289bb-7f46-48a2-88a4-2f711b4a0343.png)

Strange appearance of children subspecies in the source data:
https://www.checklistbank.org/catalogue/3/assembly?datasetKey=2232&sourceTaxonKey=2295-wcs
![image](https://user-images.githubusercontent.com/28574252/161321890-61c41f5e-c5f1-4877-a504-778f01863026.png)

_Originally posted by @yroskov in https://github.com/CatalogueOfLife/testing/issues/177#issuecomment-1086205610_

**Comment by yroskov** [comment]
_Other examples:_
**Alisma plantago-aquatica** 
https://www.checklistbank.org/catalogue/3/assembly?assemblyTaxonKey=dbeba3dc-4479-4286-87f6-49c29211cb6f&datasetKey=2232&sourceTaxonKey=294751-wcs

**Sagittaria graminea
Sagittaria guayanensis
Sagittaria lancifolia
Sagittaria montevidensis**
https://www.checklistbank.org/catalogue/3/assembly?assemblyTaxonKey=4dbbc5ac-385c-4647-820b-14b298613a86&datasetKey=2232&sourceTaxonKey=287722-wcs

**Comment by mdoering** [comment]
Indeed. I guess we should try to improve the sync so that existing species with authorships are reused. It not gonna be simple as the species might be synced after the subspecies, so we need to swap them out again if we encounter a species later on. But that should be doable.

**Comment by mdoering** [comment]
This is fixed now in production. I have tested a sync for Acoraceae and it's good now:

<img width="644" alt="image" src="https://user-images.githubusercontent.com/327505/161848620-64896334-250c-4969-935c-4b60a41645bf.png">

**Comment by yroskov** [comment]
Thanks! May I kick sync for all WCVP sectors?

**Comment by mdoering** [comment]
sure!

**Comment by yroskov** [comment]
OK. I am going ahead

**Comment by yroskov** [comment]
https://www.checklistbank.org/catalogue/3/assembly?datasetKey=2232&sourceTaxonKey=2304-wcs

Checks of 2022-04-07: CoL assembly is OK with parent-child species-subsp/var. Parent-child species-subsp/var list is flat.
