### ISSUE TITLE
CoL of June 2022

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#196]
- [x] ITIS of 2022-05-26; imported 2022-06-09; **synced 2022-06-15** 

- [x] WoRMS of 2022-06-01; 2022-06-03 import failed; re-imported
Broken sectors (2022-06-03): 
https://www.checklistbank.org/catalogue/3/sector?broken=true&limit=100&offset=0
WoRMS Copepoda = RE-ASSEMBLED & synced 2022-06-09
WoRMS Foraminifera = no problem on 2022-06-09
WoRMS Tantulocarida  = RE-ASSEMBLED & synced 2022-06-09
**synced 2022-06-07 & 09**

- [x] Scarabs of 2022-06-07 (sent twice, use second - corrected ver); imported; synced 2022-06-08

- [x] LepIndex "2022-04-39 / 2022-04-30" imported 2022-04-29; green light for assembly: DH eml of 2022-05-04; synced 2022-06-01; re-imported & synced 2022-06-02; re-synced 2022-06-08; **re-synced 2022-06-20**

- [x] Gelechiidae (new, not adopted yet, https://data.catalogueoflife.org/dataset/2362/names) imported 2022-02-11 - for March; resolved 2022-05-27; issues reported to Donald; synced 2022-05-27; new version imported 2022-05-28;  synced 2022-05-31; new version 1.1.22.159 (08 Jun 2022) / 2022-06-08; **re-synced 2022-06-08**

- [x] Systema Dipterorum, ver 3.8 received 2022-05-22; imported 2022-06-10; **synced 2022-06-13**

- [x] Nomen-Eumycetozoa, ver May 2022 received 2022-05-25; imported 2022-05-25; **synced 2022-05-26**

- [x] The Scorpion Files, ver May 2022; crawled & imported 2022-05-27; **synced 2022-06-02**

- [x] World Plants of 2022-05-29; imported; **synced 2022-06-03**

- [x] World Ferns 2022-05-29; imported; **synced 2022-06-03**

- [x] World Spider Catalog, ver. 23.0 of 2022-06-15 received 2022-06-18; **synced 2022-06-21**
>WSC: https://github.com/CatalogueOfLife/data/issues/414#issuecomment-1092924636; Hi Yuri, I will provide a new export **around June 15** when we typically compile the WSC archive version. Thanks, Daniel

- [ ] Species Fungorum Plus - Paul>"For the last few weeks I have been updating Species Fungorum and resolving some internal inconsistencies / errors in preparation for another download for COL+, partly prompted by a request from the GNI for a new download. I may have to get back to you if I forget how to ‘format’ the data, but this may be in early January.
Reminded 2022-01-25. Paul>I should be in a position to start preparing the download in the middle of May

**Other 11 GSDs for updates:** https://docs.google.com/spreadsheets/d/1WRxfYQF8h2Xiu3gNUvQ3de-zRH-BSq3wYWIAbHHBrhY/edit?usp=sharing

**Comment by gdower** [comment]
WoRMS is imported and synced except for Copepoda and Tantulocarida which have broken sectors.

Scarabs is imported but not synced.

**Comment by yroskov** [comment]
@mdoering @olafbanki, seems, syncs in CLB are faulty for last 3 days.
2022-06-13:
![image](https://user-images.githubusercontent.com/28574252/173449062-d183d03d-c0f3-4059-aa16-a601fcba6704.png)

**Comment by yroskov** [comment]
After stand-up of 2022-06-14: ITIS sync caused blockage. All above syncs cancelled. YR should repeat small syncs of Mn.

2022-06-14: kicked off syncs for Alucitoidea, Pterophoroidea & Gelechiidae 
before:
![image](https://user-images.githubusercontent.com/28574252/173623419-60ab448f-c82c-4f0e-b637-25753a1bdbfb.png)

after:
![image](https://user-images.githubusercontent.com/28574252/173623447-dbc774fe-bb8e-4f76-b73d-d9cc5be48ee4.png)

3 hours later **no progress**, all 3 are in a queue:
![image](https://user-images.githubusercontent.com/28574252/173623739-5ae64564-177d-4979-8c47-fd18f54b1d7f.png)

Reminder: **Alucitoidea, Pterophoroidea, Gelechiidae, Systema Dipterorum & ITIS should be synced.**

**Comment by yroskov** [comment]
- [ ] **Alucitoidea, Pterophoroidea, Gelechiidae, Systema Dipterorum & ITIS should be synced.**

**Comment by yroskov** [comment]
**Checks of CoL PREVIEW of 2022-06-15** at https://preview.catalogueoflife.org

- [ ] Spp numbers decreased in
LepIndex -> Global Lepidoptera Index 134812 - 133380 = 1,432 = OK (Gelechiidae replcement)
Systema Dipterorum 146206+3793-141261-3651 = 5,087 = ?
World Plants 194298 - 193945 = 353 (check Casuarinaceae, Juglandaceae, Myricaceae = OK) = OK

- [ ] New assembly of Lepidoptera
- Lepidoptera also present as a bare name in a search (it's not so in CLB): 
![image](https://user-images.githubusercontent.com/28574252/174151408-552a1a55-dac7-4b5a-ae49-5b368fd97446.png)
- nested sectors are not reflected in Lepidoptera@Tree, credits to nested families invisible in their orders.
- many empty genera in the node "Superfamily NotAssigned" (the same in CLB) 
![image](https://user-images.githubusercontent.com/28574252/174152415-fc8bd6ea-4ea1-4946-973b-bc718cf2867a.png)
https://preview.catalogueoflife.org/?taxonKey=LP--incertae-sedis--SUPERFAMILY
@dhobern, would it be better to block in the CoL all these empty genera which are dropped outside superfamilies?

**Comment by dhobern** [comment]
Yes - please drop the empty genera. They exist for various reasons and are meaningless in COL terms, but will prove useful as we carry on cleaning up sections of the Global Lepidoptera Index, so I'd like to leave them in the underlying data source for now,

**Comment by yroskov** [comment]
- [x] 690 empty genera in the node "Superfamily NotAssigned" are blocked now (selected batch - blocked selected taxa).

**Re-synced 2022-06-20**

**Comment by yroskov** [comment]
PREVIEW started 2022-06-21 (with fixes in Lepidoptera & vertebrates (Actinopterygii) classification but **without WSC**)

**Comment by yroskov** [comment]
Checks of PREVIEW 2022-06-21

- [ ] Logo for WCVP is missing, and I have no access to its metadata. There is also no option to add logo in a patch editor. @mdoering, could you pls add RBG Kew logo with WCVP?
![image](https://user-images.githubusercontent.com/28574252/175052730-ac96971d-15c2-4637-9ec0-14bb03f477b8.png)

**Comment by yroskov** [comment]
Another preview release completed on 2022-06-23. 

**CoL of 2022-06-23 released**.
