### ISSUE TITLE
CoL of August 2022, AC22

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#201]
_GT meeting 2022-06-30: AC22 should be released in Aug (no monthly edition in Aug): replace ILDIS with WCVP-Fabaceae & WoRMS Pauropoda and Symphyla with ITIS._

- [x] WoRMS of 2022-08-01; automatically imported 2022-08-02 & **synced 2022-08-02**; 31 active chklsts resolved & **re-synced 2022-08-03-05**

- [x] ITIS of 2022-08-01; imported 2022-08-03; **synced 2022-08-08**. New: family Ascidae, infraorder Procarididea, set of superfamilies in infraorder Caridea
- [x] Scarabs of 2022-08-03; synced 2022-08-03

- [x] WCVP-Fabaceae; **synced 2022-07-20**

- [ ] Species Fungorum Plus - Paul>"For the last few weeks I have been updating Species Fungorum and resolving some internal inconsistencies / errors in preparation for another download for COL+, partly prompted by a request from the GNI for a new download. I may have to get back to you if I forget how to ‘format’ the data, but this may be in early January.
2022-01-25 >I should be in a position to start preparing the download in the middle of May
2022-06-23 >If I do not complete the task by this time next week (last day of June; just over 500 left) I will just ‘hide’ the names from access via the web site and internally tag them as not yet fully looked for.

- [ ] StaphBase - distribution; awaiting a new copy

**Other 11 GSDs for updates:** https://docs.google.com/spreadsheets/d/1WRxfYQF8h2Xiu3gNUvQ3de-zRH-BSq3wYWIAbHHBrhY/edit?usp=sharing

**Comment by yroskov** [comment]
TASKS (whole CoL) as on 2022-07-26: 

![image](https://user-images.githubusercontent.com/28574252/181014061-26a74095-87d4-4245-8b82-5fcc07e9f94a.png)

**Comment by yroskov** [comment]
- [ ] **ACC-ACC sp, same authors**: 1451 duplicated spp

Lep vs GloBIS: gen Abisara in different families Lycaenidae & Riodininae
![image](https://user-images.githubusercontent.com/28574252/181015036-b049c35d-a9d7-4173-8d5f-2d668cc6a4fc.png)

WCVP vs World Plants: **Verbenaceae** - Aloysia, Bouchea, Chascanum, etc. = family Verbenaceae from both WCVP & WPlants. FIXED: Verbenaceae blocked as a child in nested sector WPlants Lamiaceae; synced.
![image](https://user-images.githubusercontent.com/28574252/181015253-d3617a30-951a-4a3c-b9a8-631cb7afb1fd.png)

Lep vs Gelechiidae
![image](https://user-images.githubusercontent.com/28574252/181017993-80ca385d-262c-45f7-a194-fb40ef454617.png)


Lep vs 3i Auchenorrhyncha
![image](https://user-images.githubusercontent.com/28574252/181017533-7923d405-a643-4ebc-bf8c-537da0a5c50f.png)

**Comment by yroskov** [comment]
Decisions in the reports across GSDs cannot be applied "in the project":
![image](https://user-images.githubusercontent.com/28574252/181078420-303538c7-fcf0-42d7-83bd-3075b80dc5f1.png)

**Comment by yroskov** [comment]
Donald, 2022-07-27
>I've fixed almost all the individual cases in GLI in TW and will reimport tonight/tomorrow.
>Two things remain:
- [ ]	please stop taking Lycaenidae from GloBIS/GART - that should fix all the Riodinidae cases = GloBIS Lycaenidae deleted; GLI Lycaenidae unblocked in assembly tree; GLI ("ver. 2022-06-30 / 2022-06-30 imported 2022-07-26") synced 2022-07-26.

- [ ] For Metasticha centrodoxa, please suppress the version from NHM Tineidae. In this case, GLI is correct. = Metasticha centrodoxa  blocked in Tineidae NHM; Tineidae sector reported as broken, re-established; synced 2022-07-

**Comment by dhobern** [comment]
Reimporting Gelechiidae will fix one of these. The others are now fixed in GLI in TW and I am exporting that to upload to CLB.

**Comment by yroskov** [comment]
**Global Lepidoptera Index**  (ver. 2022-06-30 / 2022-06-30 imported 2022-07-28) and **Gelechiidae** (ver 1.1.22.209 (28 Jul 2022) / 2022-07-28) synced 2022-07-28.

**Comment by dhobern** [comment]
Sorry about those. One of the _Torodora mindoensis_ records in GLI has been fixed to be _Torodora samarensis_ - I tripped myself up cloning a record in TW. _Telephata_ is now in Lecithoceridae, so I have removed it from the Gelechiidae dataset.

Re-importing both datasets should remove these two issues.

**Comment by yroskov** [comment]
**Gelechiidae** (ver 1.1.22.210 (29 Jul 2022) / 2022-07-29) synced 2022-07-29.

**Comment by yroskov** [comment]
PREVIEW started 2022-07-29 (13.58 Chmp)

**Comment by mdoering** [comment]
Yes, the CLB database had stuck queries because of the release and these had been killed which caused the failure. We really need to find out what it is that conflicts with a release.

**Comment by yroskov** [comment]
PREVIEW release started 2022-08-08 (13.20 in Chmp)

**Comment by yroskov** [comment]
**TESTS of preview release 2022-08-08**

**Comment by yroskov** [comment]
@olafbanki, if it's not clash with your plans, I'll do another PREVIEW release after 17.00 in Europe.

(Change after 2022-08-08 preview: ITIS adjusted their metadata)

**Comment by yroskov** [comment]
New PREVIEW started at 17.06 (Europe) 2022-08-15.

Settings:
![image](https://user-images.githubusercontent.com/28574252/184661528-71b002c0-082d-4589-bce3-2c67f0c33845.png)

**Comment by yroskov** [comment]
**TESTS of preview release 2022-08-15**:

- [x] Title: [COL Version: Annual Checklist 2022](https://preview.catalogueoflife.org/data/metadata)
- [x] ITIS metadata & stats appear as expected

The checklist looks as expected.

**Comment by yroskov** [comment]
**Preview release 2022-08-30**
