### ISSUE TITLE
Lepidoptera nested sectors: broken sectors

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#223]
After I synced Global Lepidoptera Index with a single sector "order Lepidoptera", a set of nested GSDs got broken sectors (reported as broken in Sectors tool):

Nepticuloidea (sector superfamily Nepticuloidea)
Pterophoroidea (sector superfamily Pterophoroidea)
Alucitoidea (sector superfamily Alucitoidea)
Gelechiidae (sector family Gelechiidae)
Global Gracillariidae (sector family Gracillariidae)

(GSD sectors reserved for GSDs are blocked in Global Lepidoptera Index (in assembly tool))

In the assembly Tree, these sectors appear now outside Lepidoptera: 

![image](https://user-images.githubusercontent.com/28574252/230986570-3fff7211-64e9-4c7f-96b1-2238e57ef7db.png)

@mdoering, do you have an idea what may cause this? What is a best way to repair sectors? (I keep them untouched until I get reply from you).

**Comment by mdoering** [comment]
The only reason I can think of is that the newly synced data contains the sector target name several times. This might lead to broken sectors and keeps them outside - which always happens during a sync so the nested sectors are not deleted. When the sync is done all these nested sectors are rematched and moved back. But in case the rematching fails they stay outside where they are. I need to loo into details...

**Comment by yroskov** [comment]
Welcome back! Thanks for looking on this. It would be nice to complete preview release of April on the next week.

**Comment by mdoering** [comment]
Rematching was apparently only done for subjects. I forced a target rematching with these requests and now the sectors appear fine again:

> curl -s --user USER:PASSWORD -X POST -H "Content-Type: application/json" --data-binary '{"id":1753, "target":true}' "https://api.checklistbank.org/dataset/3/sector/rematch"

**Comment by yroskov** [comment]
FIXED: https://github.com/CatalogueOfLife/testing/issues/222#issuecomment-1502258647
