### ISSUE TITLE
CoL of Apr 2021 tests: 2021-04-05 (published) 

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#29]
#### There is a new taxonomic checklist:
- [x] * [WCO: World Catalogue of Opiliones](/data/dataset/2256) - updated & synced 2021-03-18, -23

#### Six databases have been updated:

- [x] * [Alucitoidea](/data/dataset/2207) (third update) -  synced 2021-04-02
- [x] * [ITIS of 2021-02-26](/data/dataset/2144) (sixth update since AC19). New global checklists for families Varroidae (Mesostigmata), Cimicidae, Polyctenidae & Acanthosomatidae (Hemiptera), and for infraorders Astacidea and Glypheidea (Decapoda). - synced 2021-03-02.
- [x] * [Pterophoroidea](/data/dataset/1199) (third update since AC19) -  synced 2021-04-02
- [x] * [Scarabs of 2021-03-01](/data/dataset/1027) (eighth update since AC19) - synced 2021-03-02, -29.
- [x] * [World Ferns of 2021-03-17](/data/dataset/1140) (fifth update since AC19) - synced 2021-03-18.
- [x] * [World Plants of 2021-03-17](/data/dataset/1141) (fourth update since AC19) - synced 2021-03-18.

- [x] 41 WoRMS checklists synced 2021-04-02
WoRMS   Actiniaria | 1176
WoRMS Amphipoda | 1202
WoRMS Antipatharia | 1194
WoRMS Appendicularia | 1178
WoRMS Ascidiacea | 1186
WoRMS Asteroidea | 1095
WoRMS Bochusacea | 1086
WoRMS Brachypoda | 1087
WoRMS Brachyura | 1108
WoRMS Bryozoa | 1081
WoRMS Cephalochordata | 1154
WoRMS Ceriantharia | 1179
WoRMS Cestoda | 1127
WoRMS Chaetognatha | 1132
WoRMS Copepoda | 1191
WoRMS Corallimorpharia | 1195
WoRMS Ctenophora | 1180
WoRMS Cubozoa | 1181
WoRMS Cumacea | 1058
WoRMS Echinoidea | 1106
WoRMS Foraminifera | 1157
WoRMS Gastrotricha | 1122
WoRMS Gnathostomulida | 1125
WoRMS Holothuroidea | 1107
WoRMS Hydrozoa | 1112
WoRMS Isopoda | 1094
WoRMS Kinorhyncha | 1153
WoRMS Leptostraca | 1105
WoRMS Loricifera | 1182
WoRMS Merostomata | 1152
WoRMS MilliBase | 1200
WoRMS Mollusca | 1130
WoRMS Monogenea | 1126
WoRMS Ophiuroidea | 1059
WoRMS Tantulocarida | 1092
WoRMS Thaliacea | 1185
WoRMS Thermosbaenacea | 1093
WoRMS Trematoda | 1128
WoRMS Turbellarians | 1193
WoRMS Xenoturbellida | 1100
WoRMS Zoantharia | 1197

Additional fixes:
- [x] AnnonBase (old): mis-encoded diacritics in infraspecies authorstrings, "native" status, "terrestrial" spelling **fixed**; synced 2021-03-01.

**Comment by yroskov** [comment]
See also https://github.com/CatalogueOfLife/data/projects/191

**Comment by yroskov** [comment]
**41 WoRMS checklists** (2021-04-01)

_Chantal_
- [ ] WoRMS Actiniaria	1176	order Actiniaria 
- [ ] WoRMS Amphipoda	1202	order Amphipoda
- [ ] WoRMS Antipatharia	1194	order Antipatharia
- [ ] WoRMS Appendicularia	1178	class Appendicularia (sector wasn't broken)
- [ ] WoRMS Ascidiacea	1186	class Ascidiacea
- [ ] WoRMS Asteroidea	1095	class Asteroidea
- [ ] WoRMS Bochusacea	1086	order Bochusacea
- [ ] WoRMS Brachypoda	1087	order Brachypoda
- [ ] WoRMS Bryozoa	1081	phylum Bryozoa
- [ ] WoRMS Cephalochordata	1154	subphyllum Cephalochordata

_Olaf_
- [ ] WoRMS Ceriantharia	1179	subclass Ceriantharia
- [ ] WoRMS Cestoda	1127	class Cestoda in nested Platyhelmithes from WoRMS Turbellarians
- [ ] WoRMS Chaetognatha	1132	phylum Chaetognatha
- [ ] WoRMS Copepoda	1191	subclass Copepoda
- [ ] WoRMS Corallimorpharia	1195	order Corallimorpharia
- [ ] WoRMS Ctenophora	1180	phylum Ctenophora
- [ ] WoRMS Cubozoa	1181	class Cubozoa
- [ ] WoRMS Cumacea	1058	order Cumacea
- [ ] WoRMS Echinoidea	1106	class Echinoidea
- [ ] WoRMS Foraminifera	1157	phylum Foraminifera

_Geoff_
- [ ] WoRMS Gastrotricha	1122	phylum Gastrotricha
- [ ] WoRMS Gnathostomulida	1125	phylum Gnathostomulida
- [ ] WoRMS Holothuroidea	1107	class Holothuroidea
- [ ] WoRMS Hydrozoa	1112	class Hydrozoa
- [ ] WoRMS Isopoda	1094	order Isopoda
- [ ] WoRMS Kinorhyncha	1153	phylum Kinorhyncha
- [ ] WoRMS Leptostraca	1105	order Leptostraca
- [ ] WoRMS Loricifera	1182	phylum Loricifera
- [ ] WoRMS Merostomata	1152	class Merostomata
- [ ] WoRMS MilliBase	1200	classes Diplopoda, Pauropoda & Symphyla

_Yuri_
- [ ] WoRMS Mollusca	1130	phylum Mollusca
- [ ] WoRMS Monogenea	1126	class Monogenea
- [ ] WoRMS Ophiuroidea	1059	class Ophiuroidea
- [ ] WoRMS Tantulocarida	1092	subclass Tantulocarida
- [ ] WoRMS Thaliacea	1185	class Thaliacea
- [ ] WoRMS Thermosbaenacea	1093	order Thermosbaenacea
- [ ] WoRMS Trematoda	1128	class Trematoda
- [ ] WoRMS Turbellarians	1193	phylum Platyhelminthes & phylum Xenacoelomorpha (both are nested)
- [ ] WoRMS Xenoturbellida	1100	subphylum Xenoturbellida. Established as a union with classification from WoRMS Turbellarians
- [ ] WoRMS Zoantharia	1197	order Zoantharia 
- [ ] WoRMS Brachyura	1108	infraorder Brachyura is missing in the classification of WoRMS Brachyura export

**Comment by chantalhuijbers** [comment]
My check results:

 []  WoRMS Actiniaria 1176 order Actiniaria
Authors: correct
Organisation: department EEOB is part of Ohio State University, not a separate organisation. Change ; after Ohio State Uni to ,
yml file: 'Ohio State University**;** Department of Evolution, Ecology and Organismal Biology (EEOB); Kansas University Natural History Museum'

 [x]  WoRMS Amphipoda 1202 order Amphipoda
Authors and Organisation: correct

 []  WoRMS Antipatharia 1194 order Antipatharia
Authors: correct
Organisation: Toxicology and Hazard Assessment Group is part of Oak Ridge, not a separate organisation. Change ; after ORNL to ,
yml file: 'Shirshov Institute of Oceanology, Moscow, Russia; Oak Ridge National Laboratory**;** Toxicology and Hazard Assessment Group'

 [x]  WoRMS Appendicularia 1178 class Appendicularia (sector wasn't broken)
Authors and Organisation: correct

 [x] WoRMS Ascidiacea 1186 class Ascidiacea
Authors and Organisation: correct

 [x]  WoRMS Asteroidea 1095 class Asteroidea
Authors and Organisation: correct

 [x] WoRMS Bochusacea 1086 order Bochusacea
Authors and Organisation: correct

 [x]  WoRMS Brachypoda 1087 order Brachypoda
Authors and Organisation: correct

 [x]  WoRMS Bryozoa 1081 phylum Bryozoa
Authors and Organisation: correct

 [x]  WoRMS Cephalochordata 1154 subphyllum Cephalochordata
Author correct, no organisation listed.

**Comment by chantalhuijbers** [comment]
With regards to the citation:
For all checklists, it now says "Accessed at http://www.marinespecies.org on 2021-03-10", after the author, year, title.

Should this not be?: "In: Roskov Y., Ower G., Orrell T., Nicolson D., Bailly N., Kirk P. M., Bourgoin T., DeWalt R. E., Decock W., van Nieukerken E. J., Penev L. (eds.). Species 2000 & ITIS Catalogue of Life, 2020-12-01. Digital resource at www.catalogueoflife.org. Species 2000: Naturalis, Leiden, the Netherlands. ISSN 2405-8858."

**Comment by yroskov** [comment]
Thank you, @chantalhuijbers ! 

Citation should be generated automatically from GSD + CoL metadata during release. 

Honestly, I do not understand the aim of Citation field in GSD metadata.

**Comment by yroskov** [comment]
CHECKS THROUGH ALL CHECKLISTS:

Broken sectors: WoRMS Corallimorpharia & WoRMS Brachyura (not established).

**Comment by olafbanki** [comment]
[X] WoRMS Ceriantharia 1179 subclass Ceriantharia
Authors and Organisation: correct

[X] WoRMS Cestoda 1127 class Cestoda in nested Platyhelmithes from WoRMS Turbellarians
Authors and Organisation: correct
Observation: Taxonomic group lacking in ChecklistBank and yaml file

[X]  WoRMS Chaetognatha 1132 phylum Chaetognatha
Organisation change into: The Evergreen State College, Olympia, Washington, USA
Observation: Taxonomic group lacking in both ChecklistBank and yaml file

 [X]WoRMS Copepoda 1191 subclass Copepoda
Organisation change to: Smithsonian Institution, Department of Invertebrate Zoology; Natural History Museum, Department of Zoology

 [X]WoRMS Corallimorpharia 1195 order Corallimorpharia
Author change to: Fautin, D.G. [add comma remove space between initials]

[X] WoRMS Ctenophora 1180 phylum Ctenophora
Authors and Organisation: correct

[X] WoRMS Cubozoa 1181 class Cubozoa
Authors and Organisation: correct

[X] WoRMS Cumacea 1058 order Cumacea
Change organization to: University of Alaska Anchorage, Department of Biological Sciences, Anchorage, Alaska, USA

[X] WoRMS Echinoidea 1106 class Echinoidea
Authors and Organisation: correct

[X] WoRMS Foraminifera 1157 phylum Foraminifera
Authors and Organisation: correct

**Comment by yroskov** [comment]
_Yuri_
_ShortName - ID - Sector_
- [x] WoRMS Mollusca	1130	phylum Mollusca
- [x] WoRMS Monogenea	1126	class Monogenea
- [x] WoRMS Ophiuroidea	1059	class Ophiuroidea = **Move eds in Authors field, if it's doable**
- [x] WoRMS Tantulocarida	1092	subclass Tantulocarida
- [x] WoRMS Thaliacea	1185	class Thaliacea
- [x] WoRMS Thermosbaenacea	1093	order Thermosbaenacea
- [x] WoRMS Trematoda	1128	class Trematoda
- [ ] WoRMS Turbellarians **NO METADATA IN YML**	1193	
Metadata of 2019-03-05 are used. Incorrect parsing in Organisations field:
![image](https://user-images.githubusercontent.com/28574252/113422066-bcae1b80-9391-11eb-83f3-f521693abcdf.png)
_Should be two organisations:_
School of Biology and Ecology, University of Maine, Orono ME, USA 
Research group Zoology: Biodiversity and Toxicology (CMKDK), Centrum voor Milieukunde, Hasselt University, Hasselt, Belgium

- [x] WoRMS Xenoturbellida	1100	subphylum Xenoturbellida. Established as a union with classification from WoRMS Turbellarians
- [ ] WoRMS Zoantharia	1197	order Zoantharia 
Incomplete data for organisation in YML: "University of Ryukyus". Expected value: University of Ryukyus, Senbaru, Japan - **but, only if it has a sense at this point**
- [x] WoRMS Brachyura	1108	
BUT: inverted order Organisation, then its department

**Comment by yroskov** [comment]
- [ ] **WoRMS Gnathostomulida** NO YML FILE
Metadata of 2019-03-05 is used.
Incomplete organisation as "Bermuda Natural History Museum". Full value should be **Bermuda Natural History Museum, Hamilton, Bermuda** - **but, only if it has a sense at this point**

**Comment by yroskov** [comment]
**CoL of 2021-04-05**

Missing checklists in the list https://preview.catalogueoflife.org/data/contributing-datasets:
WoRMS Mystacocarida
WoRMS Priapulida
WoRMS Scleractinia
WoRMS Tanaidacea
