### ISSUE TITLE
WoRMS references as BibTex?

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/testing#41]
ColDP allows to transfer references in [3 different formats](https://github.com/CatalogueOfLife/coldp/blob/master/README.md#reference).

> References can be given in various degrees of atomization:
> 
> 1. A simple citation string is the minimum required
> 2. Semi structured using the field list below mostly corresponding to Dublin Core
> 3. Fully parsed references in the well established BibTex or CSL-JSON format. See the sections below with for how to share alternative formats that do not conform to tabular CSV/TSV files.

I see that [WoRMS offers BibTex](http://www.marinespecies.org/aphia.php?p=sourceexport&what=single&id=333976&format=bib) from their [website](http://www.marinespecies.org/aphia.php?p=sourcedetails&id=333976), so it seems to be readily available.
As BibTex offers richer, parsed data it would be great to get all references from WoRMS via BibTex!

**Comment by bart-v** [comment]
We provide CSL-JSON, so it BibTex needed too?

**Comment by mdoering** [comment]
In that case no. But I do not see the CSL in the Bryozoa data I examined. It is all DC CSV data:
https://data.catalogueoflife.org/dataset/1081/verbatim?type=col%3AReference

But maybe that's outdated?


One other reference thing. I looked up [Stomacrustula producta (Packard, 1863)](http://www.marinespecies.org/aphia.php?p=taxdetails&id=1307154) just now which has a [new combination reference](http://www.marinespecies.org/aphia.php?p=sourcedetails&id=333976) given. This does not exist in the [ColDP data](https://data.catalogueoflife.org/dataset/1081/name/urn:lsid:marinespecies.org:taxname:1307154) it seems.  `PublishedInID` is empty. Is this maybe missing because its not an original name?

**Comment by mdoering** [comment]
@bart-v how does Aphia internally manage reference metadata? is this CSL? Just curious as references are still such a pain.

**Comment by bart-v** [comment]
- There is both "Reference.txt" and "Reference JSON-CSL.json" in the Bryozoa ColDP ZIP file we provide to you.
- The reference link to Stomacrustula producta (Packard, 1863) is in in the file "NameReference.txt", it's just not annotated with "new combination reference"
```
nameID	referenceID	page	link	remarks	
urn:lsid:marinespecies.org:taxname:1307154	333976		http://www.marinespecies.org/aphia.php?p=sourcedetails&id=333976		
```
- We manage references in a table with the usual fields (author/year/title/journal/suffix) 
http://www.marinespecies.org/structure/tables/sources.html

**Comment by mdoering** [comment]
Thanks Bart.

 - `Reference.json` needs to be the name of the [CSL file in ColDP](https://github.com/CatalogueOfLife/coldp/blob/master/README.md#reference-json-csl) so it is understood. Similar it would be `Reference.bib` for a BibTex version.
 - could you also include the reference link for Stomacrustula producta in the Name.publishedInId? The NameReference table is really just for supplying pointers (page, link) within a reference for individual names. So when a single articles covers 100 names you can point out specific parts of the reference and point directly at a table,  page, etc while specifying in remarks why this is special. Otherwise references are linked via the referenceID property of nearly all other tables and mostly accept a list of ids by concatenating them with pipes.

**Comment by bart-v** [comment]
OK, done, both will be available in the next export.
