### ISSUE TITLE
Metadata in WoRMS checklists: test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#69]
The problem: metadata have not been updated in the clearinghouse after an import of all WoRMS checklists on 2021-03-10.

Bart wrote on 2021-03-23:
>we have now included the eml.xml in the ZIP file for all CoLDP exports

**Comment by yroskov** [comment]
I am testing results for **WoRMS Amphipoda** after a new import:
https://data.catalogueoflife.org/dataset/2248/meta

**Comment by yroskov** [comment]
![image](https://user-images.githubusercontent.com/28574252/112318367-f6d53a00-8c7a-11eb-97b6-b4e8019f2956.png)

**Comment by yroskov** [comment]
For attention of @gdower

**Completely missing data:**

Logo
Alias
Version
Authors
Editors
Geographic scope
Checklist Confidence
Completeness

**"Strange data** in following fields (however, if WoRMS editors are fine with them, new CoL will be also OK with them):

_Organisations:_ (1) WoRMS Editorial Board is listed among organisations.
(2) Department is listed after the organisation.

_Description:_ now text says "An authoritative classification and catalogue of marine names."
In previous CoL, it said "The amphipods belong to the very diverse crustacean class Malacostraca, which includes other common groups such as crabs, lobsters and shrimp. The order Amphipoda is part of the superorder Peracarida, uniting a diverse group of small shrimp-like taxa that brood their young in a pouch, with no independent larval dispersal stage. It currently contains over 10k species."

_English name of the group_ ("Taxonomic coverage"): incorrectly says "biota". Expected: Amphipods

_License_: says "other". Expected: correct WoRMS license

**Comment by bart-v** [comment]
Many of these are correct in metadata.yml
Cant they not be merged?

**Comment by yroskov** [comment]
**Test of newly uploaded metadata** for 7 checklists:
WoRMS Actiniaria
WoRMS Amphipoda
WoRMS Antipatharia
WoRMS Appendicularia
WoRMS Ascidiacea
WoRMS Asteroidea
WoRMS Bochusacea

**Comment by yroskov** [comment]
Common "features" for all checklists:
- [ ] **Alias** (=Short name): empty field. @gdower, _do we have a solution for this on our end?_ 
- [ ] **Organisations**: 
"WoRMS Editorial Board" is listed as an organisation at the top of the list. @bart-v, _is it as WoRMS expected in CoL?_  
Full checklist title is listed as an organisation at the bottom of the list. @bart-v, _is it as WoRMS expected in CoL?_  
Some of the checklist have these two values only.
Example:
![image](https://user-images.githubusercontent.com/28574252/112384923-fa89b080-8cbc-11eb-8cf4-2347d93050a4.png)

- [ ] **Description**: one phrase applied with all tested checklists: "An authoritative classification and catalogue of marine names" @bart-v, _is it as WoRMS expected in CoL?_  
- [ ] **Version**: empty. @gdower, _can we fix it on our side?_
- [ ] **Authors**/**Editors**: empty 
- [ ] **Website**: empty in 4 checklists of 7. 
Example, Actiniaria:
![image](https://user-images.githubusercontent.com/28574252/112385756-fb6f1200-8cbd-11eb-8b99-750d399a1bf7.png)
- [ ] **Taxonomic Group**: stated "Biota" everywhere. (CoL expects English name of the top group in this field). @bart-v, is "biota" OK with WoRMS authors?
- [ ] **Geographic scope**: stated "World Oceans" everywhere. (CoL expects values "Global" or "Regional"). @gdower, _can we fix it on our side, believing that we receive exceptionally global checklists from WoRMS?_ 
- [ ] **License**: empty
- [ ] **Checklist Confidence**: empty
- [ ] **Completeness**: empty

**Comment by yroskov** [comment]
@gdower & @bart-v 

Could field Authors in CoL be filled from the field Citation? Seems, it has a list which we exactly need:

Amphipoda:
![image](https://user-images.githubusercontent.com/28574252/112392001-c1eed480-8cc6-11eb-9837-865233c2a473.png)

Asteroidea:
![image](https://user-images.githubusercontent.com/28574252/112392055-d632d180-8cc6-11eb-86c6-3e79b62d9c1f.png)

**Comment by bart-v** [comment]
(1) the authors are available in the EML, this is why we wanted the EML support in the first place.
If combining EML and meta.yaml is too difficult, we can reconsider.

(2) Some fields in the EML are indeed defaulted to WoRMS (and not adapted to the specific list yet): we will tackle that on some point. But I would like to wait for that until we have decided to use metadata.yml, eml.xml or if both can be used.

**Comment by mdoering** [comment]
there should be 2 metadata files with information to be merged. Either we use EML or the coldp metadata.yaml.
If possible metadata.yaml is our preference and close to what was delivered in the old ACEF format already.

@gdower I have updated the yaml parser to parse out authors and organisations if they are given in a single, concatenated string like it was in ACEF. The following example now works on dev where this is deployed, try out the [metadata validator](https://data.dev.catalogueoflife.org/tools/metadata-validator) with this:

```
title: World Amphipoda Database
authorsAndEditors: Horton, T.; Lowry, J.; De Broyer, C.; Bellan-Santini, D.; Coleman, C.O.; Corbari, L.; Costello, M.J.; Daneliya, M.; Dauvin, J.-C.; Fišer, C.; Gasca, R.; Grabowski, M.; Guerra-García, J.M.; Hendrycks, E.; Hughes, L.; Jaume, D.; Jazdzewski, K.; Kim, Y.-H.; King, R.; Krapp-Schickel, T.; LeCroy, S.; Lörz, A.-N.; Mamos, T.; Senna, A.R.; Serejo, C.; Sket, B.; Souza-Filho, J.F.; Tandberg, A.H.; Thomas, J.D.; Thurston, M.; Vader, W.; Väinölä, R.; Vonk, R.; White, K.; Zeidler, W. 
organisations: Field Museum of Natural History; Bavarian State Collection of Zoology (ZSM)
```

Only semicolons are recognized as delimiters.

**Comment by mdoering** [comment]
This is the latest version of the metadata.yaml:
https://github.com/CatalogueOfLife/coldp/blob/master/metadata.yaml

Note that COL is currently discussing an [update to the metadata model](https://github.com/CatalogueOfLife/backend/issues/989). It might be that in a few months the exact version might slightly change, but we will make sure the current version is still supported. And if you want to upgrade it would only be small changes, the basic YAML will stay the same.

**Comment by mdoering** [comment]
Can you link the EML from those archives? Maybe there was an empty shortName element and there was no alias in the patch. We should prevent those cases that the EML set an alias back to NULL - Ill fix that today still.

**Comment by yroskov** [comment]
Unblocking solution: take metadata from metadata.yml, not from eml.xml (files of 2021-03-23, exmpl https://github.com/CatalogueOfLife/worms-metadata/tree/main/WoRMS_Actiniaria)  

Modifications needed before the import: 
- Short Name: replace underscore with space: WoRMS_Actiniaria -> WoRMS Actiniaria
- Released: change date 2021-03-23 to 2021-03-10 (because it should reflect date of the content, not date of metadata)

**Comment by bart-v** [comment]
FYI

We now generate a fully CoLDP compliant metadata.yml, and no EML
Will be available on 2021-06-01

After verification, can we
* close this issue
* remove this repo https://github.com/CatalogueOfLife/worms-metadata
