### ISSUE TITLE
WoRMS: how good is CoL of 2021-04-05 view

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#75]
- 41 WoRMS checklists have been updated (https://github.com/CatalogueOfLife/testing/issues/29).

- Preview release is available at  https://preview.catalogueoflife.org/
 
- Species counts in 11 checklists are identical to AC19:
WoRMS Appendicularia | 1178
WoRMS Bochusacea | 1086 
WoRMS Brachypoda | 1087
WoRMS Cephalochordata | 1154
WoRMS Ceriantharia | 1179
WoRMS Corallimorpharia | 1195
WoRMS Cumacea | 1058
WoRMS Gnathostomulida | 1125
WoRMS Tantulocarida | 1092
WoRMS Thaliacea | 1185
WoRMS Xenoturbellida | 1100

**Comment by yroskov** [comment]
@olafbanki @chantalhuijbers, could you please help to compare data view in CoL vs WoRMS website (http://www.marinespecies.org/) for a few checklists listed below.

_What we are looking for? integrity in the classification, especially, missing or "inserted" taxa. If any spotted, please report them below._

WoRMS Amphipoda | 1202 - plus 139 spp vs ac19
WoRMS Echinoidea | 1106 - plus 121 spp vs ac19
WoRMS Holothuroidea | 1107 - plus 7 spp vs ac19
WoRMS Zoantharia | 1197 - minus 6 spp vs ac19

Probably, the most complicated cases are:
WoRMS Mollusca | 1130 - plus 20,917 spp vs ac19
WoRMS Trematoda | 1128 - plus 1,443 spp vs ac19

**Comment by chantalhuijbers** [comment]
Check for WoRMS Amphipoda checklist in COL preview against WoRMS (http://www.marinespecies.org/amphipoda/)

3 suborders are entirely the same: Colomastigidea (2 families; 3 genera; 59 species), Hyperiopsidea (3 families; 5 genera; 15 species), Pseudingolfiellidea (1 families; 1 genera; 4 species).

Differences between COL and WoRMS:
Suborder Hyperiidea: COL has 1 family and 2 genera more than WoRMS, but same number of species.

Difference in family numbers and 1 genus is caused in Superfamily Scinoidea. COL has Family Proscinidae listed separately, but WoRMS has this as accepted as Mimonectidae.

COL preview:
superfamily: Scinoidea Stebbing, 1888
family: Archaeoscinidae K. H. Barnard, 1930
family: Microscinidae Zeidler, 2012
family: Mimonectidae Bovallius, 1885
family: Mimoscinidae Zeidler, 2012
family: Proscinidae
family: Scinidae Stebbing, 1888
 
WoRMS:
Family Archaeoscinidae K. H. Barnard, 1930
Family Microscinidae Zeidler, 2012
Family Mimonectidae Bovallius, 1885
Family Mimoscinidae Zeidler, 2012
Family Scinidae Stebbing, 1888

Family Proscinidae Pirlot, 1933 accepted as Mimonectidae Bovallius, 1885
Family Tyronidae Bovallius, 1887 accepted as Scinidae Stebbing, 1888

http://www.marinespecies.org/amphipoda/aphia.php?p=taxdetails&id=325393&allchildren=1

Difference in other genus is caused in Family Parascelidae, which in COL has genus Hemiscelus, which is an unaccepted genus in WoRMS,  accepted as Hemityphis in Family Parasceiidae.

COL preview:
family: Parascelidae Bovallius, 1887
genus: Eusceliotes Stebbing, 1888
genus: Hemiscelus
genus: Parascelus Claus, 1879
genus: Schizoscelus Claus, 1879
genus: Thyropus Dana, 1852

WoRMS:
Genus Eusceliotes Stebbing, 1888
Genus Parascelus Claus, 1879
Genus Schizoscelus Claus, 1879
Genus Thyropus Dana, 1852

Genus Euscelus Claus, 1879 accepted as Eusceliotes Stebbing, 1888 (junior homonym)
Genus Hemiscelus Stewart, 1913 accepted as Hemityphis Claus, 1879 (junior subjective synonym)
Genus Tanyscelus Claus, 1879 accepted as Thyropus Dana, 1852

I have not checked the suborders Amphilochidea and Senticaudata yet. @yroskov is this the kind of information that you want?

**Comment by yroskov** [comment]
Thank you @chantalhuijbers. Brilliant report.

Taxa without authorstrings came into CoL classification from "flat tables". Is it serious mistake? I don't think so. 

If you go to the page of Proscina scinoides (Woltereck, 1906)  (child species in family Proscinidae) http://www.marinespecies.org/aphia.php?p=taxdetails&id=550641, pls check the classification above the species: family Proscinidae is present there. 

However, if you go to family Proscinidae http://www.marinespecies.org/aphia.php?p=taxdetails&id=325393, you will find that this family has Unaccepted status. 

Ideally, taxa with Unaccepted status should be marked as Provisionally Accepted in CoLDP, if they are really needed in the classification.

**Comment by yroskov** [comment]
>I have not checked the suborders Amphilochidea and Senticaudata yet. @yroskov is this the kind of information that you want?

No, reported sample is perfectly enough.

**Comment by chantalhuijbers** [comment]
@yroskov thanks, I can do the other two suborders (Amphilochidea and Senticaudata) in Amphipoda tomorrow.

**Comment by yroskov** [comment]
Of course, you are welcome to continue checks. Could you, please, try to check synonyms with species, if possible.

**Comment by chantalhuijbers** [comment]
I have checked a large part of the suborder Amphilochidea in the order Amphipoda and cannot find anything that is different between COL preview and WoRMS. According to the statistics, COL would have 2 more genera (691 in COL vs 689 in WoRMS, and 2 more species (4156 vs 4154), but I haven't come across any differences. Both sources list 88 families.

**Comment by yroskov** [comment]
Thank you! That's good. We can go for April release - Bart gave us a green light.
