### ISSUE TITLE
SF Plecoptera on DEV

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#78]
SF Plecoptera, id 1065
exported from https://sandcastle.taxonworks.org 2021-04-07

https://data.dev.catalogueoflife.org/dataset/1065/imports

Import: 3225 spp vs 3938 in ac19 = lost 713 spp

**Comment by yroskov** [comment]
- [ ] Species counts in newly imported version 713 species less than they were in ac19 (3225 spp vs 3938 in ac19).

- [ ] Lot of species is in the Tree root (i.e. outside order Plecoptera)

![image](https://user-images.githubusercontent.com/28574252/113922265-b6160e80-97ac-11eb-8688-b06d2c49edb1.png)

- [x] Rest of the Tree looks good

**Comment by yroskov** [comment]
**Plecoptera imported 2021-05-21** https://data.dev.catalogueoflife.org/dataset/2150/classification

- [x] Imported **4278** spp vs 3938 in ac19 (+340)

- [x] Classification: no taxa outside Plecoptera
![image](https://user-images.githubusercontent.com/28574252/119197389-45217200-ba4d-11eb-84dc-83c0dc9c40fa.png)

- [x] Original combination is in place

- [ ] Only few empty taxa spotted in the tree, for example,
genus †Palaeonemourica Sinitshenkova, 2004 (misspelling for †Palaeonemourisca Sinitshenkova, 2004)

![image](https://user-images.githubusercontent.com/28574252/119197874-0dff9080-ba4e-11eb-8d7b-045c343ceff4.png)

**Comment by debpaul** [comment]
Hi @redewalt

**Comment by debpaul** [comment]
Test comment.
