### ISSUE TITLE
SF Orthoptera on DEV

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#87]
SF Orthoptera, id 1021
https://data.dev.catalogueoflife.org/dataset/1021/classification

- [ ] Loss of species: imported 26439 spp vs 28111 in ac19 (-1,672 spp)

**Comment by yroskov** [comment]
- [ ] Classification:
https://data.dev.catalogueoflife.org/dataset/1021/classification
23 subfamilies, 1 tribe, many genera, many species and many subspecies are in the Tree root (i.e. outside order Orthoptera)

Example:
![image](https://user-images.githubusercontent.com/28574252/114240392-0fb53f00-994d-11eb-92ee-133d7d7fb97e.png)

![image](https://user-images.githubusercontent.com/28574252/114240447-1fcd1e80-994d-11eb-9e4d-a45c0948f677.png)

![image](https://user-images.githubusercontent.com/28574252/114240465-278cc300-994d-11eb-8920-8b358776f0f8.png)

![image](https://user-images.githubusercontent.com/28574252/114240496-36737580-994d-11eb-8a0b-003bb03e85ad.png)

![image](https://user-images.githubusercontent.com/28574252/114240549-4d19cc80-994d-11eb-945e-c71cec1b227b.png)

**Comment by yroskov** [comment]
As I can see, in each case of the orphan child, its parent marked in the clearinghouse as "bare name".

Example:

According TW, subfamily Cachoplistinae is a child of family Phalangopsidae. However, family Phalangopsidae marked as "bare name" in the clearinghouse:

https://data.dev.catalogueoflife.org/catalogue/3/dataset/1021/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&q=Phalangopsidae

**Comment by yroskov** [comment]
_Example 2:_

**Genus Anarchita** is a child of subtribe Pyrgomorphina:
https://sandcastle.taxonworks.org/tasks/nomenclature/browse?taxon_name_id=22132

Subtribe Pyrgomorphina marked as "bare name" in the clearinghouse:
https://data.dev.catalogueoflife.org/catalogue/3/dataset/1021/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&q=Pyrgomorphina

**Comment by yroskov** [comment]
_Example 3:_

**Species Anaxipha delicatula** is a child of superspecies Anaxipha supersp. delicatula:
https://sandcastle.taxonworks.org/tasks/nomenclature/browse?taxon_name_id=29679

**Anaxipha supersp delicatula** marked as "bare name". It looks like Clearinghouse did not accept superspecies as a rank:
https://data.dev.catalogueoflife.org/catalogue/3/dataset/1021/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&q=Anaxipha&reverse=false

**Comment by LocoDelAssembly** [comment]
@yroskov @gdower I uploaded a new dataset where it seems the invalid parent problem is fixed (but at the same time a lot of them were introduced with synonyms, not because of the changes I made in TW).

https://data.dev.catalogueoflife.org/dataset/2128/classification
![image](https://user-images.githubusercontent.com/4991925/114277854-582f3400-9a03-11eb-88e7-dbda2ae23ab3.png)
![image](https://user-images.githubusercontent.com/4991925/114277996-0509b100-9a04-11eb-840d-e767af949839.png)

For reference here is import without changes applied on export: https://data.dev.catalogueoflife.org/dataset/2129/classification (please feel free to delete this dataset)
![image](https://user-images.githubusercontent.com/4991925/114278116-8bbe8e00-9a04-11eb-924b-70196f9eec09.png)
![image](https://user-images.githubusercontent.com/4991925/114278010-1c489e80-9a04-11eb-9785-00d216949d3e.png)

**Comment by yroskov** [comment]
@LocoDelAssembly Hernan, is a new version of Orthoptera SF available in the sandcastle at https://sandcastle.taxonworks.org/?

**Comment by LocoDelAssembly** [comment]
@yroskov the data is 6 months old, but the import itself was last run 14 days ago with modifications to the import code. The CoLDP export I generated comes from the same data Sandcastle currently has.

**Comment by gdower** [comment]
@LocoDelAssembly, the project names include a timestamp from over a month ago like: `aphid_species_file(2021-03-08 13:26:13 +0000)`. That must not be the import time? I took the most recent dump from sandcastle to work on the exporter issues summary.

**Comment by LocoDelAssembly** [comment]
The latest is at sandcastle. That timestamp changes only when importing from scratch, but most of the time I start from the last steps.

If you need newer data please let me know. Need Rich to prepare me a fresher SQL Server database for that.

**Comment by yroskov** [comment]
New dataset from Hernán: https://data.dev.catalogueoflife.org/dataset/2128/classification 

Classification looks good.

(So far one empty subfamily:
![image](https://user-images.githubusercontent.com/28574252/114781882-e9254880-9d3e-11eb-9c54-73bbb750eed7.png)

**Comment by LocoDelAssembly** [comment]
mmmh, that subfamily looks it is actually a synonym: http://orthoptera.speciesfile.org/Common/basic/Taxa.aspx?TaxonNameID=1114999

Also considered valid in Sandcastle so this is an error from OSF import (checked source database and it is indeed NameStatus=7, i.e. synonym):
![image](https://user-images.githubusercontent.com/4991925/114796007-4680c000-9d66-11eb-9916-08a3022bc419.png)

**Comment by yroskov** [comment]
https://data.dev.catalogueoflife.org/dataset/2128/classification (of 2021-04-10) 
assessed on 2021-04-15

- [x] Growth of species!: now imported 29024 spp vs 28111 in ac19 (+ 913 spp)

- [ ] Classification: as I can see, a number of "empty" taxa in the Tree is really small:
Few examples, just in case:
Subfamily Ommatolampinae Brunner von Wattenwyl, 1893

Subfamily Erianthi Karsch, 1889
![image](https://user-images.githubusercontent.com/28574252/114928625-6cef3b80-9df8-11eb-8545-1758718414df.png)

Tribe Erianthini Karsch, 1889
![image](https://user-images.githubusercontent.com/28574252/114928821-ab84f600-9df8-11eb-9b89-dd443598b952.png)

Tribe Chrotogonidae Bolívar, 1904
![image](https://user-images.githubusercontent.com/28574252/114929190-19312200-9df9-11eb-8993-f7d18836b86a.png)

Tribe Tristirae Rehn, 1906
![image](https://user-images.githubusercontent.com/28574252/114928409-2f8aae00-9df8-11eb-8ce5-78b52ba8c18c.png)

Tribe Atacamacridini Carbonell & Mesa, 1972
![image](https://user-images.githubusercontent.com/28574252/114928453-3addd980-9df8-11eb-84ba-95f7f7b68c4b.png)

genus Mexitettix Otte, 2007
![image](https://user-images.githubusercontent.com/28574252/114927176-d1110000-9df6-11eb-972b-30b32f467b2c.png)

genus Opomala non Stål, 1873
![image](https://user-images.githubusercontent.com/28574252/114927767-788e3280-9df7-11eb-92bf-d00c7d9deaf3.png)

genus Xyphicera non Kirby, 1910
![image](https://user-images.githubusercontent.com/28574252/114928133-dd498d00-9df7-11eb-9c25-e5544f0f1a02.png)



![image](https://user-images.githubusercontent.com/28574252/114926741-55af4e80-9df6-11eb-9a96-5a389938c1c6.png)

**Comment by gdower** [comment]
It looks like some empty taxa are valid but just empty:

http://sandcastle.taxonworks.org/tasks/nomenclature/browse?taxon_name_id=11988

Some are invalid:

http://sandcastle.taxonworks.org/tasks/nomenclature/browse?taxon_name_id=21712

**Comment by LocoDelAssembly** [comment]
> Some are invalid:
>
>http://sandcastle.taxonworks.org/tasks/nomenclature/browse?taxon_name_id=21712

That one would be bad SF import or bad CoLDP export?

Mexitettix the problem likely is that the species are all under temporary names causing the entire subtrees to be excluded from import.

**Comment by yroskov** [comment]
**SF Orthoptera imported on DEV 2021-05-19**:
https://data.dev.catalogueoflife.org/dataset/1021/classification

**Comment by yroskov** [comment]
**Test of the version imported on 2021-05-20**: https://data.dev.catalogueoflife.org/dataset/2146/classification

- [ ] Classification: many taxa are outside Orthoptera: genera, species, subspecies

![image](https://user-images.githubusercontent.com/28574252/119009755-13c77a00-b959-11eb-9259-bcc36c58ff83.png)
![image](https://user-images.githubusercontent.com/28574252/119009828-217cff80-b959-11eb-91fa-8aeafcfdc77c.png)
![image](https://user-images.githubusercontent.com/28574252/119009936-38235680-b959-11eb-9e38-f39bd41c1c5d.png)

**Comment by yroskov** [comment]
- [ ] Examples of empty taxa in the Tree (I would say, very small number of "empty taxa" - improved!):
_All detected examples:_
tribe Erianthini Karsch, 1889
families Eneopteridae Saussure, 1874; Oecanthidae Blanchard, 1845
subfamily Ommatolampinae Brunner von Wattenwyl, 1893
genus Traulia Stål, 1873

![image](https://user-images.githubusercontent.com/28574252/119010792-08c11980-b95a-11eb-8a4c-4e9a29a62d3b.png)
![image](https://user-images.githubusercontent.com/28574252/119011847-0f03c580-b95b-11eb-9e73-9b88f8da4594.png)
![image](https://user-images.githubusercontent.com/28574252/119012171-673ac780-b95b-11eb-90b4-fce8ecf416cc.png)
![image](https://user-images.githubusercontent.com/28574252/119012722-e3cda600-b95b-11eb-9745-c093c3c6bc97.png)

**Comment by yroskov** [comment]
Test of the version imported on 2021-05-21: https://data.dev.catalogueoflife.org/dataset/1021/classification

- [x] Imported **29030 spp** vs 28111 in ac19 

- [x] Classification: OK. No taxa outside Orthoptera!
![image](https://user-images.githubusercontent.com/28574252/119151222-cc062880-ba14-11eb-9080-ca0012cfcc43.png)

- [ ] Empty taxa in the Tree: there are few
_Examples:_
subfamily Ommatolampinae Brunner von Wattenwyl, 1893 https://data.dev.catalogueoflife.org/dataset/1021/classification?taxonKey=3521
genus Libellula non Stål, 1873  https://data.dev.catalogueoflife.org/dataset/1021/classification?taxonKey=12955

![image](https://user-images.githubusercontent.com/28574252/119151549-1edfe000-ba15-11eb-8e64-b209f7ad41d7.png)
![image](https://user-images.githubusercontent.com/28574252/119152077-96ae0a80-ba15-11eb-811f-855cc584b028.png)

**Comment by yroskov** [comment]
- [ ] It looks like, basionyms are not included in synonymy again, and marked by the clearinghouse as bare names

_Examples_

Gryllacris carrikeri Hebard, 1927 is basionym for Abelona carrikeri (Hebard, 1927)
